### ISSUE TITLE
Add a Reminder System for New Arrivals/Existing Users

### ISSUE THREAD

**Issue by anishprasad01** [Chris-Johnston/CSSBot#22]
Add a reminder system that reminds new arrivals to the server to check the `#readme` channel, as well as change their nicknames to their actual names. Potentially also add a similar reminder to existing users who have neglected to change their names, or are engaging in behavior that is against server rules.

**Comment by Chris-Johnston** [comment]
Alternate idea would be to direct message new users as they join to prevent spam in the general channel. Can also ensure that everyone gets to read the rules.
